[package]
authors = ["Austin Tindle <tindleaj@gmail.com>"]
edition = "2018"
name = "cimple"
version = "0.1.0"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"

[[bin]]
doc = true
name = "dispatcher"

[[bin]]
doc = true
name = "observer"
