[package]
authors = ["Austin Tindle <tindleaj@gmail.com>"]
edition = "2018"
name = "cimple"
version = "0.1.0"

[dependencies]
clap = "2"
serde = {version = "1.0.114", features = ["derive"]}
serde_json = "1.0.56"
